### ISSUE TITLE
Add global cleanup

### ISSUE THREAD

**Issue by marquesm91** [mpeyper/react-hooks-testing-library#13]
I love [react-testing-library](https://github.com/kentcdodds/react-testing-library) and would be interesting if [react-hooks-testing-library](https://github.com/mpeyper/react-hooks-testing-library) have the same clean up behavior.

So besides this

```js
import { cleanup } from 'react-hooks-testing-library';

afterEach(cleanup);
```

We could have one more way to do that and use the same approach as react-testing-library and use it in setup files

```js
import 'react-hooks-testing-library/cleanup';
// or
import 'react-hooks-testing-library/cleanup-after-each';
```

The implementation could be the same as react-testing-library

```js
// cleanup-after-each.js or just cleanup.js
afterEach(require('./dist').cleanup);

// to make sense to react-hooks-testing-library just change to /lib
afterEach(require('./lib').cleanup);
```

So the test suites would be more cleaner and you don't have to worry about cleanups. I would love to open a PR for this. 😁

**Comment by mpeyper** [comment]
> I would love to open a PR for this. 😁

Well, don't let me stand in your way.  Just make sure you [add yourself as a contributor](https://github.com/mpeyper/react-hooks-testing-library/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) before you're done.
