### ISSUE TITLE
How to wrap a hook with a Provider?

### ISSUE THREAD

**Issue by stramel** [mpeyper/react-hooks-testing-library#23]
### What is your question:

How can I wrap a hook with a necessary Provider?

**Comment by mpeyper** [comment]
Hi @stramel, you can use the `wrapper` option of `renderHook` to wrap the test component in anything you want.  An example of using a context `Provider` can be seen [in our test suite](https://github.com/mpeyper/react-hooks-testing-library/blob/master/test/useContext.test.js#L17)

```js
const wrapper = ({ children }) => (
  <YourContext.Provider value="bar">{children}</YourContext.Provider>
)

const { result } = renderHook(() => useYourHook(), { wrapper })
```

Please feel free to submit a PR improving the docs as some examples are definitely missing.

**Comment by stramel** [comment]
@mpeyper Thank you for the answer. This is indeed what I was looking for. I will try to get a PR out for this in the near future.

**Comment by mpeyper** [comment]
Thanks.  I've added an item to #19 for `wrapper` documentation.  I'll close this one now and any PR can be made against that.
