### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [mpeyper/react-hooks-testing-library#5]
I just saw the package is updated to `v0.3.3`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @mpeyper! 🙂

**Comment by mpeyper** [comment]
Fair point.  I've added some details to the [releases](https://github.com/mpeyper/react-hooks-testing-library/releases) page and will endeavour to update it with releases.  I'm not going to worry with anything pre-v3.0.0 as that was before it was `testHook` compatible.
