### ISSUE TITLE
Cannot find module 'react-test-renderer'

### ISSUE THREAD

**Issue by mtinner** [mpeyper/react-hooks-testing-library#52]
### What is your question:

I'm getting an error `Cannot find module 'react-test-renderer' from 'index.js'` when I am executing my tests.
Currently I don't have react-test-renderer listed in my package.json. But I saw it as a peer dependency in the package.json of react-hooks-testing-library.

Do I have to install the peerDependency by my own?
I'm using v0.5

**Comment by mpeyper** [comment]
Yes. The reason it's a peer dependency is that it should be the same version as react, so we don't want to provide our own version and have them get out of sync.

**Comment by mtinner** [comment]
thank you 🎉maybe this should be added to the readme?

**Comment by mpeyper** [comment]
Yes, probably a good idea. Would including in the installation instructions be sufficient?

Happy if you want to contribute that.

**Comment by hellooldfriend** [comment]
I had the same issue, but versions were equal. Solved by installing this: npmjs.com/package/@types/react-test-renderer
