### ISSUE TITLE
 (0 , _reactTestRenderer.act) is not a function

### ISSUE THREAD

**Issue by lrojas94** [mpeyper/react-hooks-testing-library#66]
- `react-hooks-testing-library` version: 0.5.0
- `react-testing-library` version: 16.8.3
- `react` version: 16.8.2
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 1.13.0

### Relevant code or config:

```js
  it('allows to upload photos through the mutation', async () => {
    const { result, nextUpdate } = renderHook(() =>
      usePhotosUpload({
        photosUploadMutation,
      }),
    );

    act(() => {
      result.current.onPhotoUpload({
        files: [file],
        accountId: 'my-account',
      });
    });

    await nextUpdate();

    expect(photosUploadMutation).toHaveBeenCalled();
  });
```

### What you did:

Run `yarn test`

### What happened:
```
TypeError: (0 , _reactTestRenderer.act) is not a function

      13 | 
      14 |   it('allows to upload photos through the mutation', async () => {
    > 15 |     const { result, nextUpdate } = renderHook(() =>
         |                                    ^
      16 |       usePhotosUpload({
      17 |         photosUploadMutation,
      18 |       }),

      at renderHook (../../../node_modules/react-hooks-testing-library/lib/index.js:151:30)
      at Object._callee$ (__test__/hooks/usePhotosUpload.test.js:15:36)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (__test__/hooks/usePhotosUpload.test.js:13:103)
      at _next (__test__/hooks/usePhotosUpload.test.js:15:194)
      at __test__/hooks/usePhotosUpload.test.js:15:364
      at Object.<anonymous> (__test__/hooks/usePhotosUpload.test.js:15:97)
```

### Problem description:

Getting the error above whenever I try to use `renderHook`.

**Comment by lrojas94** [comment]
Reinstalled all packages and it worked. Sorry for the trouble.

**Comment by pedro-mass** [comment]
🤔 Seeing the same thing...

- `react-hooks-testing-library`: ^0.5.0
- `react-testing-library`: ^6.0.2
- `react`: ^16.8.6,
- `node`: v11.10.1
- `yarn`: 1.16.0

**Comment by mpeyper** [comment]
Do you have `react-test-renderer` installed too? Requiring that was the breaking change for `v0.5.0`

**Comment by ericmatte** [comment]
> Do you have react-test-renderer installed too? Requiring that was the breaking change for v0.5.0

Indeed; we need to also install this.
The [documentation for peer-dependencies](https://github.com/testing-library/react-hooks-testing-library#peer-dependencies) currently says:

> It also does not come installed with a specific renderer, we currently support react-test-renderer and react-dom. You only need to install one of them, however, if you do have both installed, we will use react-test-renderer as the default.

I think that maybe this should be updated to reflect the breaking change.

**Comment by joshuaellis** [comment]
I dont think the documentation needs updating. IT's clear you have to install a specific renderer and this issue is nearly 2years old.

**Comment by mpeyper** [comment]
To be clear, that is an old comment. We used to only support `react-test-renderer` but now we support either that or `react-dom`. The `react-test-renderer` is only required if you didn't have `react-dom` installed or if you are bundling the code for some reason , but even then I would suggest [being specific](https://react-hooks-testing-library.com/installation#being-specific) instead of installing an extraneous dependency.

**Comment by nemonemi** [comment]
I am actually experiencing this now.
The hook that I'm having does no mutations, just parses and returns data.

For a hook:
```ts
export function useRowFormat(): RowFormat {
  const getAvailability = useAvailability();
  const getExpirationStatus = useExpirationStatus();

  return (data) => {
    const { properties, id, type } = data;
    // adjust the data within this scope
   return // the adjusted data
  }
}
```

I have a test like this:
```ts
const { result } = renderHook(() => useRowFormat());
expect(result.current(data)).toEqual({
...
```
It fails with `(0 , _reactTestRenderer.act) is not a function`.

**Comment by hhimanshu** [comment]
https://react-hooks-testing-library.com/installation#being-specific as mentioned in the [comment](https://github.com/testing-library/react-hooks-testing-library/issues/66#issuecomment-820742803) helped me.

I had to change my import from 
```
import { renderHook } from "@testing-library/react-hooks";
```
to 
```
import { renderHook } from "@testing-library/react-hooks/server";
```
and I am using `"react-test-renderer": "18.1.0",` installed using the following command

```
yarn add -D @testing-library/react-hooks react-test-renderer
```

**Comment by essential-randomness** [comment]
If people are still having problems, make sure that the version of `react-test-renderer` is the same as the version of React you have installed.
