### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by BrianMitchL** [mpeyper/react-hooks-testing-library#7]
React Testing Library ships with TypeScript types, and when moving to use `renderHook` from this react-hooks-testing-library, there are no types declared.

This seems like the types could mostly be re-exported from react-testing-library, and pull in what it had for `testHook` before removing it in v6.0.0: https://github.com/kentcdodds/react-testing-library/commit/12d934abd14990d0164c83f1574b13f6d386ce3f#diff-494415c3af35245ecae73f5d42d8b331L55

**Comment by mpeyper** [comment]
Other than the rename from testHook (while also still exists) to renderHook, there has also been a new option added (initialProps) and a parameter added to rerender (newProps).

Happy for someone to contribute these.

**Comment by otofu-square** [comment]
Can I work on this issue? :smile:

**Comment by mpeyper** [comment]
Absolutely!
