### ISSUE TITLE
Can rerender avoid unmounting?

### ISSUE THREAD

**Issue by RubenVerborgh** [mpeyper/react-hooks-testing-library#9]
`rerender` currently seems to always `unmount` the hook, causing the `useEffect` cleanup hooks to be called etc. This means that it is not easy to test repeated invocations of a hook.

**Comment by mpeyper** [comment]
Hi @RubenVerborgh,

The rerender function is more or less a reexport from `react-testing-library`.  Can you elaborate more on what the behaviour you are seeing is and what your expected behaviour is?  An example test, codesandbox, or repro repo are also really handy if you have one.

**Comment by RubenVerborgh** [comment]
My goal is to test in what circumstances `useEffect` would re-execute, versus those were it does not. So I want to be able to change the input parameters sent to the hook (for instance, through props), without necessarily causing `useEffect` to refire.

Currently, it seems that `rerender` always refires `useEffect`, whereas I only want it to retrigger when needed (as specified by the second argument of `useEffect`).

**Comment by snakeUni** [comment]
Hi @mpeyper 
`source code`
```
function useCounter(initialValue: number) {
  const [count, setCount] = useState(initialValue)

  const incrementBy = (step: number) => {
    setCount(count + step)
  }

  const decrementBy = (step: number) => {
    setCount(count - step)
  }

  const increment = () => {
    setCount(count + 1)
  }

  const decrement = () => {
    setCount(count - 1)
  }

  return [count, {
    increment,
    decrement,
    decrementBy,
    incrementBy
  }]
}
```
`test code`
```
describe('useCounter Test', () => {
  afterEach(cleanup)
  it('should use counter', () => {
    const { result } = renderHook(() => useCounter(1))
    const count = result.current[0]
    expect(count).toBe(1)
  })
  it('increment count', () => {
    const { result } = renderHook(() => useCounter(1))
    const { increment, incrementBy } = result.current[1]
    act(() => increment())
    expect(result.current[0]).toBe(2)
    act(() => incrementBy(2))
    expect(result.current[0]).toBe(4)
  })
})
```
`test result`
![image](https://user-images.githubusercontent.com/17973020/53779312-a3c8a700-3f3a-11e9-8791-68f830f99195.png)
why not 4 ?

**Comment by mpeyper** [comment]
@snakeUni firstly, your problem did not seem related to this one, so probably should have been a separate issue (but I'm not so strict that I won't help you here anyway, just for next time).

It works if you change the test to:

```js
it('increment count', () => {
  const { result } = renderHook(() => useCounter(1))
  act(() => result.current[1].increment())
  expect(result.current[0]).toBe(2)
  act(() => result.current[1].incrementBy(2))
  expect(result.current[0]).toBe(4)
}
```

Yours didn't work because the `increment` and `incrementBy` variables you were setting with the line `const { increment, incrementBy } = result.current[1]` had closed over the original `count` value  of`1`, so the `incrementBy(2)` call was correctly incrementing `1` by `2`, resulting in `3`.

By using `result.current[1].incrementBy(2)`, the test now gets the updated `incrementBy` function from the second time `useCounter` was rendered (triggered by the `increment()` call), which has closed over the updated `count` value (`2`), so the resulting value is the expected `4`.

Does that make sense?

**Comment by mpeyper** [comment]
@RubenVerborgh You'll need to show me what your test looks likes as I'm not able to reproduce that behaviour.

I tried setting up an example test and it appears to be functioning correctly:

```js
const sideEffect = {
  [1]: { started: false, finished: false },
  [2]: { started: false, finished: false }
}

function useSideEffect(id) {
  useEffect(() => {
    sideEffect[id].started = true
    return () => {
      sideEffect[id].finished = true
    }
  }, [id])
}

test('should handle not trigger useEffect hook cleanup if props do not change', () => {
  const { rerender, unmount } = renderHook(({ id }) => useSideEffect(id), {
    initialProps: { id: 1 }
  })

  // first side effect initialised
  expect(sideEffect[1].started).toBe(true)
  expect(sideEffect[1].finished).toBe(false)
  expect(sideEffect[2].started).toBe(false)
  expect(sideEffect[2].finished).toBe(false)

  rerender()

  // nothing changed
  expect(sideEffect[1].started).toBe(true)
  expect(sideEffect[1].finished).toBe(false)
  expect(sideEffect[2].started).toBe(false)
  expect(sideEffect[2].finished).toBe(false)

  rerender({ id: 2 })

  // first side effect cleaned up, second side effect initialised
  expect(sideEffect[1].started).toBe(true)
  expect(sideEffect[1].finished).toBe(true)
  expect(sideEffect[2].started).toBe(true)
  expect(sideEffect[2].finished).toBe(false)

  rerender()

  // nothing changed
  expect(sideEffect[1].started).toBe(true)
  expect(sideEffect[1].finished).toBe(true)
  expect(sideEffect[2].started).toBe(true)
  expect(sideEffect[2].finished).toBe(false)

  unmount()

  // all side effects cleaned up
  expect(sideEffect[1].started).toBe(true)
  expect(sideEffect[1].finished).toBe(true)
  expect(sideEffect[2].started).toBe(true)
  expect(sideEffect[2].finished).toBe(true)
})
```

**Comment by RubenVerborgh** [comment]
The above indeed seems like the behavior I'd need, so let's assume react-hooks-library is indeed doing the right thing. I hit this issue while deep in other code, and it appeared to function differently. I will close for now, but reopen if I can reproduce. Thanks for looking into this.

**Comment by snakeUni** [comment]
Thank you,  it helps me. Next time , I will create a new issue.😊

**Comment by kasir-barati** [comment]
@RubenVerborgh @mpeyper here is the reproducible error. I hope we can have a discussion on what I am doing or understanding wrong about react testing library. See ya there.

https://github.com/testing-library/react-testing-library/issues/1264
